version: '3.8'

services:
  mysql:
    build:
      context: ./mysql-init
    container_name: db01
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: accounts

  memcached:
    image: memcached:latest
    container_name: mc01
    restart: always
    command: memcached -m 64 -p 11211 -u root -l 0.0.0.0
    ports:
      - "11211:11211"

  rabbitmq:
    image: rabbitmq:latest
    container_name: rmq01
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
      RABBITMQ_CONFIG_FILE: /etc/rabbitmq/rabbitmq.conf
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_management load_definitions \"/etc/rabbitmq/definitions.json\""
    volumes:
      - ./rabbitmq-config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      - ./rabbitmq-config/definitions.json:/etc/rabbitmq/definitions.json

  vprofile-app:
    build:
      context: ./app
    container_name: vprofile-web
    ports:
      - "8080" #no host port is listen, you have to access the tomcat frontend via the nginx
    depends_on:
      - mysql
      - memcached
      - rabbitmq

  nginx:
    image: nginx:latest
    container_name: vprofile-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - vprofile-app

